# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/medrobotics/kinect_streamer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/medrobotics/kinect_streamer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/medrobotics/kinect_streamer/CMakeFiles /home/medrobotics/kinect_streamer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/medrobotics/kinect_streamer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kinect_recorder

# Build rule for target.
kinect_recorder: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kinect_recorder
.PHONY : kinect_recorder

# fast build rule for target.
kinect_recorder/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinect_recorder.dir/build.make CMakeFiles/kinect_recorder.dir/build
.PHONY : kinect_recorder/fast

#=============================================================================
# Target rules for targets named kinect_viewer

# Build rule for target.
kinect_viewer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kinect_viewer
.PHONY : kinect_viewer

# fast build rule for target.
kinect_viewer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinect_viewer.dir/build.make CMakeFiles/kinect_viewer.dir/build
.PHONY : kinect_viewer/fast

src/kinect_recorder.o: src/kinect_recorder.cpp.o
.PHONY : src/kinect_recorder.o

# target to build an object file
src/kinect_recorder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinect_recorder.dir/build.make CMakeFiles/kinect_recorder.dir/src/kinect_recorder.cpp.o
.PHONY : src/kinect_recorder.cpp.o

src/kinect_recorder.i: src/kinect_recorder.cpp.i
.PHONY : src/kinect_recorder.i

# target to preprocess a source file
src/kinect_recorder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinect_recorder.dir/build.make CMakeFiles/kinect_recorder.dir/src/kinect_recorder.cpp.i
.PHONY : src/kinect_recorder.cpp.i

src/kinect_recorder.s: src/kinect_recorder.cpp.s
.PHONY : src/kinect_recorder.s

# target to generate assembly for a file
src/kinect_recorder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinect_recorder.dir/build.make CMakeFiles/kinect_recorder.dir/src/kinect_recorder.cpp.s
.PHONY : src/kinect_recorder.cpp.s

src/kinect_viewer.o: src/kinect_viewer.cpp.o
.PHONY : src/kinect_viewer.o

# target to build an object file
src/kinect_viewer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinect_viewer.dir/build.make CMakeFiles/kinect_viewer.dir/src/kinect_viewer.cpp.o
.PHONY : src/kinect_viewer.cpp.o

src/kinect_viewer.i: src/kinect_viewer.cpp.i
.PHONY : src/kinect_viewer.i

# target to preprocess a source file
src/kinect_viewer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinect_viewer.dir/build.make CMakeFiles/kinect_viewer.dir/src/kinect_viewer.cpp.i
.PHONY : src/kinect_viewer.cpp.i

src/kinect_viewer.s: src/kinect_viewer.cpp.s
.PHONY : src/kinect_viewer.s

# target to generate assembly for a file
src/kinect_viewer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinect_viewer.dir/build.make CMakeFiles/kinect_viewer.dir/src/kinect_viewer.cpp.s
.PHONY : src/kinect_viewer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... kinect_recorder"
	@echo "... kinect_viewer"
	@echo "... src/kinect_recorder.o"
	@echo "... src/kinect_recorder.i"
	@echo "... src/kinect_recorder.s"
	@echo "... src/kinect_viewer.o"
	@echo "... src/kinect_viewer.i"
	@echo "... src/kinect_viewer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

